### ISSUE TITLE
why not generate intermediate code ?

### ISSUE THREAD

**Issue by dslu7733** [DoctorWkt/acwj#25]
This project is excellent!  I learn a lot from it. But I am curious why not  generate intermediate code in your project?  Will it look a little "incomplete" ?

**Comment by DoctorWkt** [comment]
The compiler is complete in that it compiles itself. I didn't want to write a production compiler. If I added an intermediate representation, that would have added hundreds more lines of code. I could also improve the register allocation but, again, that would add hundreds more lines of code.

Both of these things could be added to the existing compiler, but the compiler works without them.

**Comment by bencz** [comment]
Well, I believe that the purpose is to teach and not complicate .... implementing an IR would really create a very big problem ... this project already has the basic of a compiler, which is the purpose of the project ...

"In this Github repository, I'm documenting my journey to write a self-compiling compiler for a subset of the C language. I'm also writing out the details so that, if you want to follow along, there will be an explanation of what I did, why, and with some references back to the theory of compilers."

**Comment by DoctorWkt** [comment]
I solved the problem by using someone else's intermediate code: QBE!
Cheers, Warren
